---
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Api for retrieving onica id's"
Parameters:
  DDBTable:
    Type: String
    Description: DynamoDB Table name
  DDBTableArn:
    Type: String
    Description: DynamoDB Table Arn
Resources:
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: DynamoDBRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
                Effect: Allow
                Resource: !Ref DDBTableArn
        -
          PolicyName: BasicExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"

  TestEntries:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "lambda.main"
      Runtime: "python3.6"
      CodeUri: "entries/"
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      Environment:
        Variables:
          DDBTable: !Ref DDBTable
      Events:
        ListEntries:
          Type: "Api"
          Properties:
            Path: "/id"
            Method: "GET"
        DisplayEntry:
          Type: "Api"
          Properties:
            Path: "/id/{id_number}"
            Method: "GET"
  TestEntriesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub '/aws/lambda/${TestEntries}'
Outputs:
  ApiUrl:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage'
